In [ ]:
#Problem - 1: Array Creation:

#1. Initialize an empty array with size 2X2.
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)

#2. Initialize an all one array with size 4X2.
import numpy as np
all_one_array = np.ones((4, 2))
print(all_one_array)

#3. Return a new array of given shape and type, filled with fill value.
import numpy as np
shape = (3, 3)
fill_value = 7
dtype = np.int32
filled_array = np.full(shape, fill_value, dtype=dtype)
print(filled_array)

#4. Return a new array of zeros with same shape and type as a given array.
import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6]],dtype=np.int32)
zeros_array = np.zeros_like(original_array)
print(zeros_array)

#5. Return a new array of ones with same shape and type as a given array.
import numpy as np
original_array = np.array([[2, 4, 6], [8, 10, 12]], dtype=np.float64)
ones_array = np.ones_like(original_array)
print(ones_array)

#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.
import numpy as np
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)


[[4.82930995e-310 0.00000000e+000]
 [4.82878131e-310 6.88375799e-310]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0 0]
 [0 0 0]]


AttributeError: module 'numpy' has no attribute 'ones_likes'

In [ ]:
#Problem - 3: Array Operations:
'''For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
'''
#1. Add the two array.
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])


result = x + y
print(result)

'''For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
'''

#2. Subtract the two array.
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result = x - y
print(result)

#3. Multiply the array with any integers of your choice.
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result_x = x * 3
result_y = y * 3

print(result_x)
print(result_y)

#4. Find the square of each element of the array.
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result_x = np.square(x)
result_y = np.square(y)

print(result_x)
print(result_y)

#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print(dot_vw)
print(dot_xv)
print(dot_xy)

#6. Concatenate x(and)y along row and Concatenate v(and)w along column.
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_xy_row = np.concatenate((x, y), axis=0)  # Along rows
concat_vw_col = np.vstack((v, w))  # Along columns

print(concat_xy_row)
print(concat_vw_col)

#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
import numpy as np

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

concat_xv = np.concatenate((x, v), axis=0)
print(concat_xv)







[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[15 18]
 [21 24]]
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#Problem - 4: Matrix Operations:
'''• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:'''
#1. Prove A.A−1 = I.
import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
result = np.round(result, decimals=10)

print("Matrix A:")
print(A)

print("\nInverse of A (A^-1):")
print(A_inv)

print("\nProduct A * A^-1:")
print(result)

#2. Prove AB ̸= BA.
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nProduct AB:")
print(AB)

print("\nProduct BA:")
print(BA)

#3. Prove (AB)
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
B_T_A_T = np.dot(B_T, A_T)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nProduct AB:")
print(AB)

print("\nTranspose of AB (AB^T):")
print(AB_T)

print("\nTranspose of B (B^T) and A (A^T) product (B^T * A^T):")
print(B_T_A_T)

#B.
import numpy as np

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([[-1], [-3], [9]])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution (x, y, z):")
print(X)

#Now: solve the above equation using np.linalg.inv function.
import numpy as np

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([[-1], [-3], [9]])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

X_direct = np.linalg.solve(A, B)

det_A = np.linalg.det(A)

print("Solution using inverse method (x, y, z):")
print(X)

print("\nDirect solution using np.linalg.solve (x, y, z):")
print(X_direct)

print("\nDeterminant of A:")
print(det_A)







In [ ]:
#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np
array = np.arrange(10, 50)
print(array)

#2. Create a 3X3 matrix with values ranging from 0 to 8.
import numpy as np
array = np.arange(9)
matrix = np.reshape(array, (3,3))
print(matrix)

#3. Create a 3X3 identity matrix.{Hint:np.eye()}
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

#4. Create a random array of size 30 and find the mean of the array.
import numpy as np
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array", random_array)
print("Mean of the array", mean_value)

#5. Create a 10X10 array with random values and find the minimum and maximum values.
import numpy as np
random_array = np.rndom.random((10, 10))
min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 array:\n", random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

#6. Create a zero array of size 10 and replace 5th element with 1.
import numpy as np
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

#7. Reverse an array arr = [1,2,0,0,4,0].
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print(reversed_arr)

#8. Create a 2d array with 1 on border and 0 inside.
import numpy as np
size = 5
array = np.zeros((size,size))
array[0, :] = 1
array[-1, :] = 1
array[:, -1] = 1
array[:, -1] = 1

print(array)

#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np
checkboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print (checkerboard)
